title: Wiicreation
email: coreyw.ultimatemedia@gmail.com
description: The Wiicreation Website source containing docs, downloads and more.
tagline: Wiicreation is a recreation of the Nintendo Wii made in ElectronJS.
baseurl: /WiicreationWebsite
url: https://C1200.js.org
twitter_username: C1200Games
github_username: C1200
aux_links:
  GitHub:
    - //github.com/C1200/Wiicreation
collections:
  docs:
    permalink: /:collection/:path/
    output: true
just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_exclude: false
      search_exclude: false
back_to_top: true
back_to_top_text: Back to top
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
lastupdate:
  date: Fri 09 Apr 2021 04:01:04 PM BST
  user: C1200
